### PR TITLE
Fixed heist chests

### PR DESCRIPTION
**Pull request by Dubzzzzy**
Quick-Fixed icons of secondary chests in heists, removed goto

### CODE REVIEW

**Comment by Dubzzzzy** [comment]
@Queuete How could I contact you?

**Comment by Queuete** [comment]
Heist Icons are handled in a specific Heist plugin: https://github.com/IlliumIv/HeistIcons

If you want to contact me in private your best bet is the OwnedCore forum.

**Comment by Dubzzzzy** [comment]
Okay, but how should I use minimapIcons and HeistIcons together?

**Comment by Queuete** [comment]
I dont really get that question. Simply activate them both?

**Comment by Dubzzzzy** [comment]
image
They are conflicting with each other, but I found a parameter to hide heist icon in IconsBuilder settings

**Pull request closed without merging**
